before_script:
  - docker info
  - nvidia-smi

.build:
  script:
    - docker build -t ${CI_JOB_ID} --build-arg IMAGE=$IMAGE .
    - docker run --rm --runtime nvidia --env CUARRAYS_MEMORY_LIMIT $CI_JOB_ID -e '
          using Pkg;
          run(`nvcc --version`);
          Pkg.test(collect(keys(Pkg.installed())));'
    - docker rmi ${CI_JOB_ID}

cuda:10.1:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04'
  allow_failure: true # https://github.com/JuliaGPU/CuArrays.jl/pull/431
                      # not part of a tagged version of CuArrays.jl yet

cuda:10.0:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04'

cuda:9.2:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04'

cuda:9.0:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04'
  allow_failure: true # https://github.com/JuliaGPU/CuArrays.jl/issues/295
                      # probably an issue with CUDA 9.0
