before_script:
  - docker info
  - nvidia-smi

.build:
  script:
    - docker build -t ${CI_JOB_ID} --build-arg IMAGE=$IMAGE .
    - docker run --rm --runtime nvidia $CI_JOB_ID -e 'using Pkg;
                                                      run(`nvcc --version`);
                                                      Pkg.test(collect(keys(Pkg.installed())));'
    - docker rmi ${CI_JOB_ID}

cuda:10.1:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04'

cuda:10.0:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04'

cuda:9.2:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04'

cuda:9.0:
  extends: .build
  variables:
    IMAGE: 'nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04'
