before_script:
  - docker info

build_image:
  script:
    - docker build -t ngc .
    - docker run --runtime nvidia ngc -e 'using Pkg;
                                          Pkg.test(collect(keys(Pkg.installed())));'
