name: update_packages

on: push

jobs:
  update_packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.1]  # NOTE: keep this in sync with the Dockerfile
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@082493e5c5d32c1fa68c35556429b0f1b2807453 # v1.0.1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'import Pkg; Pkg.add(["GitCommand", "GitHub"])'
      - name: Update packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'include("tools/update_packages.jl"); "${{ github.repository }}" == "maleadt/julia-ngc" && main("${{ github.repository }}"; cc_usernames = String["@maleadt"])'
