name: update_packages

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1.0.2
        with:
          version: '1.3.1'  # NOTE: keep this in sync with the Dockerfile
      - name: Update packages
        id: update
        run: |
          log=$(julia --project -e "using Pkg; Pkg.update()")
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "::set-output name=log::$log"
      - name: Get status
        id: status
        run: |
          log=$(julia --project -e "using Pkg; Pkg.status()")
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "::set-output name=log::$log"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update packages.

            ${{ steps.status.outputs.log }}
          title: Update packages
          reviewers: maleadt
          body: |
            Updates the following packages:

            ```
            ${{ steps.status.outputs.log }}
            ```

            <details><summary>Click here for the update log.</summary>
            <p>

            ```
            ${{ steps.update.outputs.log }}
            ```

            </p>
            </details>
          branch: update_packages
